
version: "3"
services:
  smartide-golang-vmlc-go-dev:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-golang-v2-jetbrains-goland-vmlc:latest
    runtime: sysbox-runc
    hostname: dev-container
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123       
    volumes:
      - .:/home/project
    ports:
      - 6822:22
      - 6800:8887
    networks:
      - smartide-network  

networks:
  smartide-network:
    external: true