
version: "3"
services:
  smartide-vmlc-vscode-dotnet-dev:
    image: registry.cn-hangzhou.aliyuncs.com/smartide/smartide-dotnet-v2-vscode-vmlc:latest
    runtime: sysbox-runc
    hostname: dev-container
    restart: always
    environment:
      LOCAL_USER_PASSWORD: root123       
    volumes:
      - .:/home/project
    ports:
      - 6822:22
      - 6800:3000
    networks:
      - smartide-network  

networks:
  smartide-network:
    external: true